# Generated by Django 4.2.16 on 2025-10-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_date_joined"),

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True, default=None, null=True, upload_to="avatars/"
            ),
        ),
    ]
